Extensions
smartprix/babel-changed pull request #4
Opened 2020-06-22 18:18 UTC by rohit-gohri

Closes #2 

- Add extensions support
- Upgrade dependencies
- Update readme

2020-06-22 18:39 UTC, pubkey commented
Wow. Thank you very much.

2020-06-23 13:09 UTC, hit12369 requested changes

2020-06-23 13:09 UTC, hit12369 commented on index.js
> +			if (extensions.reduce((result, extension) => result ||srcFile.endsWith(extension), false)) {
`Array.some` can be used here instead.

2020-06-23 13:09 UTC, hit12369 commented
Great work :+1:

2020-06-23 13:18 UTC, hit12369 commented on bin/babel-changed.js
> +	extensions: program.extensions.split(',').filter(Boolean),
Extensions should be trimmed, in case someone uses `-e "js, mjs, ts"`

2020-06-24 04:20 UTC, hit12369 approved these changes

2020-06-24 04:21 UTC, merged